# Generated by Django 4.2.1 on 2023-05-27 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deneme',
        ),
    ]
